
services:
  mongo_trd:
    image: mongo:latest
    container_name: mongo_trd
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - docker_network_trd
#    volumes:
#      - ./mongo-init:/docker-entrypoint-initdb.d

  kafka-trd:
    image: apache/kafka:latest
    container_name: kafka-trd
    networks:
      - docker_network_trd
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka-trd:9092,CONTROLLER://kafka-trd:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-trd:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-trd:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3



  mongo-express_trd:
    image: mongo-express:latest
    container_name: mongo-express_trd
    depends_on:
      - mongo_trd
      - kafka-trd
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo_trd:27017/
    networks:
      - docker_network_trd

  trd-control-server:
    image: trd-control-server:1.0.0
    container_name: trd-control-server
    depends_on:
      - mongo_trd
    ports:
      - "8080:8080"
    networks:
      - docker_network_trd
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongo_trd:27017/admin?authSource=admin
      SPRING_PROFILES_ACTIVE : docker

networks:
  docker_network_trd:
    driver: bridge

