# Trade Control Server Configuration
server.port=5001

# MongoDB Configuration
spring.data.mongodb.username=admin
spring.data.mongodb.password=admin
spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017
#spring.data.mongodb.uri=mongodb://admin:admin@mongo_trd:27017
spring.data.mongodb.database=trdDB

# Logging
logging.level.com.apurv.tradecontrol=DEBUG
